name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Obtener el código
        uses: actions/checkout@v4.2.2

      - name: Configurar Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Verificar que existe el frontend
        run: ls ./frontend

      # --- BACKEND ---
      - name: Instalar dependencias (backend)
        working-directory: ./backend
        run: npm install

      - name: Build (backend)
        working-directory: ./backend
        run: npm run build

#      - name: Tests (backend)
#        working-directory: ./backend
#        run: npm tests